import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { PIGMENTS, paintCss, ragBox, strokes, worstContrast } from '../../scripts/paint/paint.mjs';
import { parseRules, splitSelectors } from '../helpers/css';

const read = (rel: string): string => readFileSync(new URL(`../../${rel}`, import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const SCOPE = ':root[data-variant="data"]';
/** The SVG of a `url("data:image/svg+xml,…")` value. */
const svgOf = (value: string): string => decodeURIComponent(/^url\("data:image\/svg\+xml,(.*)"\)$/.exec(value)?.[1] ?? '');

describe('brush paint (scripts/paint/paint.mjs → src/styles/paint.css, DS-2)', () => {
  const css = read('src/styles/paint.css');
  const decls = parseRules(css).find((r) => r.selector === SCOPE)?.decls ?? new Map<string, string>();

  it('paint.css is exactly what paint.mjs generates (regenerate with --write)', () => {
    expect(css).toBe(paintCss());
    expect(css.startsWith('/* generated by scripts/paint/paint.mjs — do not edit')).toBe(true);
  });

  it('pigment bases equal --ed-red/--ed-blue/--ed-yellow in tokens.css', () => {
    const root = parseRules(read('src/styles/tokens.css')).find((r) => r.selector === ':root' && r.media === null)?.decls;
    expect([PIGMENTS.r.base, PIGMENTS.b.base, PIGMENTS.y.base]).toEqual([root?.get('--ed-red'), root?.get('--ed-blue'), root?.get('--ed-yellow')]);
    for (const [k, token] of [['r', '--ed-red'], ['b', '--ed-blue'], ['y', '--ed-yellow']] as const) {
      expect(decls.get(`--ed-paint-${k}h`)).toBe(`var(--tex-${k}h), var(${token})`);
      expect(decls.get(`--ed-paint-${k}v`)).toBe(`var(--tex-${k}v), var(${token})`);
    }
  });

  it('analytic worst case: white on red ≥ 4.6 at the lightest streak, white on blue ≥ 7, ink on yellow ≥ 7 at the darkest', () => {
    const red = worstContrast('r', '#FFFFFF');
    const blue = worstContrast('b', '#FFFFFF');
    const yellow = worstContrast('y', '#141414');
    expect(red.atLightest).toBeGreaterThanOrEqual(4.6);
    expect(red.atDarkest).toBeGreaterThan(red.atLightest);
    expect(Math.min(blue.atLightest, blue.atDarkest)).toBeGreaterThanOrEqual(7);
    expect(yellow.atDarkest).toBeGreaterThanOrEqual(7);
    expect(yellow.atLightest).toBeGreaterThan(yellow.atDarkest);
  });

  it('each texture is an 800×400 or 400×800 SVG with stitched, tiled turbulence (seamless) and no CSS colour literal', () => {
    for (const k of ['r', 'b', 'y']) {
      for (const [d, w, h] of [['h', 800, 400], ['v', 400, 800]] as const) {
        const svg = svgOf(decls.get(`--tex-${k}${d}`) ?? '');
        expect(svg).toMatch(new RegExp(`^<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}'>`));
        expect(svg.match(/<feTurbulence [^>]*stitchTiles='stitch'/g)).toHaveLength(4);
        expect(svg.match(/<feTile /g)).toHaveLength(4);
        expect(svg).toContain("color-interpolation-filters='sRGB'");
        expect(svg).not.toMatch(/#[0-9a-f]{3,8}\b|rgba?\(|\b(black|white|red|blue|yellow|gr[ae]y)\b/i);
      }
    }
    // the direction swaps the frequencies; dark and light tints are the pigment's own (never black or grey)
    expect(strokes(true, 3, [0, 0, 0], [0, 0, 0], 0.3, 0.075)).toContain("baseFrequency='0.0017 0.045'");
    expect(strokes(false, 3, [0, 0, 0], [0, 0, 0], 0.3, 0.075)).toContain("baseFrequency='0.045 0.0017'");
    expect(css).not.toMatch(/#[0-9a-fA-F]{3,8}\b|\brgba?\(|\bhsla?\(/);
  });

  it('the rag box is a closed path inside its 132 px box with every corner point inset; slice 6 and 3 px variants', () => {
    const svg = svgOf(decls.get('--ragbox') ?? '');
    expect(svg).toBe(ragBox());
    const d = /<path d='([^']+)'\/>/.exec(svg)?.[1] ?? '';
    expect(d.startsWith('M') && d.endsWith('Z')).toBe(true);
    const pts = d.slice(1, -1).split('L').map((p) => p.split(' ').map(Number));
    expect(pts.length).toBeGreaterThan(200);
    for (const [x, y] of pts) {
      expect(x).toBeGreaterThan(0);
      expect(y).toBeGreaterThan(0);
      expect(x).toBeLessThan(132);
      expect(y).toBeLessThan(132);
    }
    for (const corner of [[2.4, 2.4], [129.6, 2.4], [129.6, 129.6], [2.4, 129.6]]) expect(pts).toContainEqual(corner);
    expect(decls.get('--ed-rag')).toBe('var(--ragbox) 6 / 6px round');
    expect(decls.get('--ed-rag-s')).toBe('var(--ragbox) 6 / 3px round');
  });

  it('paint.css declares only custom properties, under :root[data-variant="data"]', () => {
    const rules = parseRules(css);
    expect(rules).toHaveLength(1);
    expect(splitSelectors(rules[0]!.selector)).toEqual([SCOPE]);
    expect([...rules[0]!.decls.keys()].filter((name) => !name.startsWith('--'))).toEqual([]);
    expect(rules[0]!.decls.size).toBe(6 + 1 + 2 + 6);
    expect(read('src/layouts/DataLayout.astro')).toMatch(/import '\.\.\/styles\/paint\.css';/);
    for (const f of ['BaseLayout', 'NeutralLayout']) expect(read(`src/layouts/${f}.astro`), f).not.toContain('paint.css');
  });
});
