import { readFileSync } from 'node:fs';
import { sep } from 'node:path';
import { describe, expect, it } from 'vitest';
import sharp from 'sharp';
import { PIGMENTS, TILES, paintCss, ragBox, strokes, tileFile, tileSvg, worstContrast } from '../../scripts/paint/paint.mjs';
import { parseRules, splitSelectors } from '../helpers/css';

const read = (rel: string): string => readFileSync(new URL(`../../${rel}`, import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const SCOPE = ':root[data-variant="data"]';
/** The SVG of a `url("data:image/svg+xml,…")` value. */
const svgOf = (value: string): string => decodeURIComponent(/^url\("data:image\/svg\+xml,(.*)"\)$/.exec(value)?.[1] ?? '');

describe('brush paint (scripts/paint/paint.mjs → src/styles/paint.css, DS-2)', () => {
  const css = read('src/styles/paint.css');
  const decls = parseRules(css).find((r) => r.selector === SCOPE)?.decls ?? new Map<string, string>();
  // Deferred textures (DS-9 ruling): the tiles attach after the load event, the stroke tile on the first hover/focus.
  const TEX = `${SCOPE}[data-paint-tex]`;
  const STROKE = `${SCOPE}[data-paint-stroke]`;
  const texDecls = parseRules(css).find((r) => r.selector === TEX)?.decls ?? new Map<string, string>();
  const strokeDecls = parseRules(css).find((r) => r.selector === STROKE)?.decls ?? new Map<string, string>();
  const tokenRoot = () => parseRules(read('src/styles/tokens.css')).find((r) => r.selector === ':root' && r.media === null)?.decls;

  it('paint.css is exactly what paint.mjs generates (regenerate with --write)', () => {
    expect(css).toBe(paintCss());
    expect(css.startsWith('/* generated by scripts/paint/paint.mjs — do not edit')).toBe(true);
  });

  // Named change (deferred textures): a painted field's colour layer is the flat paint (the tiles' mean), so the swap
  // from flat to textured after load is barely visible.
  it('pigment bases equal --ed-red/--ed-blue/--ed-yellow in tokens.css; fields sit on the flat paint (--ed-*-paint)', () => {
    const root = tokenRoot();
    expect([PIGMENTS.r.base, PIGMENTS.b.base, PIGMENTS.y.base]).toEqual([root?.get('--ed-red'), root?.get('--ed-blue'), root?.get('--ed-yellow')]);
    for (const [k, token] of [['r', '--ed-red-paint'], ['b', '--ed-blue-paint'], ['y', '--ed-yellow-paint']] as const) {
      expect(decls.get(`--ed-paint-${k}h`)).toBe(`var(--tex-${k}h), var(${token})`);
      expect(decls.get(`--ed-paint-${k}v`)).toBe(`var(--tex-${k}v), var(${token})`);
    }
    expect(decls.get('--ed-paint-stroke')).toBe('var(--ed-stroke-tex), var(--ed-yellow-paint)');
  });

  it('the flat paint tokens are the mean colour of their tiles (each channel within 1, both scales), and text on them reads', async () => {
    const root = tokenRoot();
    const rgb = (hex: string): number[] => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
    for (const [k, token] of [['r', '--ed-red-paint'], ['b', '--ed-blue-paint'], ['y', '--ed-yellow-paint']] as const) {
      const flat = rgb(root?.get(token) ?? '#000000');
      for (const key of TILES.filter((t) => t[0] === k)) {
        for (const scale of [1, 2] as const) {
          const px = await sharp(tileFile(key, scale)).removeAlpha().raw().toBuffer();
          const mean = [0, 1, 2].map((c) => { let sum = 0; for (let i = c; i < px.length; i += 3) sum += px[i]!; return sum / (px.length / 3); });
          for (const c of [0, 1, 2]) expect(Math.abs(mean[c]! - flat[c]!), `${token} vs ${key}@${scale}x channel ${c}`).toBeLessThanOrEqual(1);
        }
      }
    }
    const lin = (v: number): number => (v / 255 <= 0.03928 ? v / 255 / 12.92 : ((v / 255 + 0.055) / 1.055) ** 2.4);
    const lum = (c: number[]): number => 0.2126 * lin(c[0]!) + 0.7152 * lin(c[1]!) + 0.0722 * lin(c[2]!);
    const ratio = (a: number[], b: number[]): number => (Math.max(lum(a), lum(b)) + 0.05) / (Math.min(lum(a), lum(b)) + 0.05);
    expect(ratio([255, 255, 255], rgb(root!.get('--ed-red-paint')!))).toBeGreaterThanOrEqual(4.5);
    expect(ratio([255, 255, 255], rgb(root!.get('--ed-blue-paint')!))).toBeGreaterThanOrEqual(7);
    expect(ratio([0x14, 0x14, 0x14], rgb(root!.get('--ed-yellow-paint')!))).toBeGreaterThanOrEqual(7);
  });

  it('analytic worst case: white on red ≥ 4.6 at the lightest streak, white on blue ≥ 7, ink on yellow ≥ 7 at the darkest', () => {
    const red = worstContrast('r', '#FFFFFF');
    const blue = worstContrast('b', '#FFFFFF');
    const yellow = worstContrast('y', '#141414');
    expect(red.atLightest).toBeGreaterThanOrEqual(4.6);
    expect(red.atDarkest).toBeGreaterThan(red.atLightest);
    expect(Math.min(blue.atLightest, blue.atDarkest)).toBeGreaterThanOrEqual(7);
    expect(yellow.atDarkest).toBeGreaterThanOrEqual(7);
    expect(yellow.atLightest).toBeGreaterThan(yellow.atDarkest);
  });

  // Named change (textures pre-rendered): the SVG is the tiles' source (paint.mjs renders it), no longer the CSS value.
  it('each texture source is an 800×400 or 400×800 SVG with stitched, tiled turbulence (seamless) and no CSS colour literal', () => {
    expect(TILES).toEqual(['rh', 'rv', 'bh', 'bv', 'yh', 'yv']);
    for (const key of TILES) {
      const [w, h] = key.endsWith('h') ? [800, 400] : [400, 800];
      const svg = tileSvg(key);
      expect(svg).toMatch(new RegExp(`^<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}'>`));
      expect(svg.match(/<feTurbulence [^>]*stitchTiles='stitch'/g)).toHaveLength(4);
      expect(svg.match(/<feTile /g)).toHaveLength(4);
      expect(svg).toContain("color-interpolation-filters='sRGB'");
      expect(svg).not.toMatch(/#[0-9a-f]{3,8}\b|rgba?\(|\b(black|white|red|blue|yellow|gr[ae]y)\b/i);
    }
    // the direction swaps the frequencies; dark and light tints are the pigment's own (never black or grey)
    expect(strokes(true, 3, [0, 0, 0], [0, 0, 0], 0.3, 0.075)).toContain("baseFrequency='0.0017 0.045'");
    expect(strokes(false, 3, [0, 0, 0], [0, 0, 0], 0.3, 0.075)).toContain("baseFrequency='0.045 0.0017'");
    expect(css).not.toMatch(/#[0-9a-fA-F]{3,8}\b|\brgba?\(|\bhsla?\(/);
  });

  // Live feTurbulence cost 0.6–1.2 s of main-thread rasterising per data page on phones; the tiles are pre-rendered.
  // Named change (deferred textures): the tiles are declared under [data-paint-tex] (set after the load event); before
  // that every --tex-* is none and the fields show their flat paint. The stroke tile is the yellow horizontal one,
  // declared under [data-paint-stroke] (set on the first hover or focus).
  it('paint.css ships each texture as pre-rendered WebP tiles (image-set of a 1× and a 2× file), never SVG noise; attached after load', () => {
    for (const key of TILES) {
      expect(decls.get(`--tex-${key}`)).toBe('none');
      expect(texDecls.get(`--tex-${key}`)).toBe(`image-set(url("./paint/paint-${key}.webp") 1x, url("./paint/paint-${key}-2x.webp") 2x)`);
      expect(tileFile(key, 1).split(sep).join('/')).toMatch(new RegExp(`src/styles/paint/paint-${key}\\.webp$`));
      expect(tileFile(key, 2).split(sep).join('/')).toMatch(new RegExp(`src/styles/paint/paint-${key}-2x\\.webp$`));
    }
    expect(css).not.toMatch(/feTurbulence|<filter|%3Cfilter/);
    expect(decls.get('--ed-stroke-tex')).toBe('none');
    expect(strokeDecls.get('--ed-stroke-tex')).toBe(texDecls.get('--tex-yh'));
    expect([...texDecls.keys()].sort()).toEqual(TILES.map((k) => `--tex-${k}`).sort());
    expect([...strokeDecls.keys()]).toEqual(['--ed-stroke-tex']);
  });

  it('the tiles are opaque WebP files of the tile size (1×) and twice it (2×)', async () => {
    for (const key of TILES) {
      const [w, h] = key.endsWith('h') ? [800, 400] : [400, 800];
      for (const scale of [1, 2] as const) {
        const meta = await sharp(tileFile(key, scale)).metadata();
        expect([meta.format, meta.width, meta.height, meta.hasAlpha], `${key} ${scale}x`).toEqual(['webp', w * scale, h * scale, false]);
      }
    }
  });

  it('worst pixel of the committed tiles: white on red ≥ 4.5, white on blue ≥ 7, ink on yellow ≥ 7 (both scales)', async () => {
    const lin = (v: number): number => (v / 255 <= 0.03928 ? v / 255 / 12.92 : ((v / 255 + 0.055) / 1.055) ** 2.4);
    const lum = (r: number, g: number, b: number): number => 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
    const ratio = (a: number, b: number): number => (Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05);
    const floor = { r: 4.5, b: 7, y: 7 } as const;
    const text = { r: lum(255, 255, 255), b: lum(255, 255, 255), y: lum(0x14, 0x14, 0x14) } as const;
    const minima: string[] = [];
    for (const key of TILES) {
      const pigment = key[0] as 'r' | 'b' | 'y';
      for (const scale of [1, 2] as const) {
        const px = await sharp(tileFile(key, scale)).removeAlpha().raw().toBuffer();
        let worst = Infinity;
        for (let i = 0; i < px.length; i += 3) worst = Math.min(worst, ratio(text[pigment], lum(px[i]!, px[i + 1]!, px[i + 2]!)));
        minima.push(`${key}@${scale}x ${worst.toFixed(2)}`);
        expect(worst, `${key} ${scale}x`).toBeGreaterThanOrEqual(floor[pigment]);
      }
    }
    console.info(`paint tiles, worst text contrast: ${minima.join(', ')}`);
  });

  it('the rag box is a closed path inside its 132 px box with every corner point inset; slice 6 and 3 px variants', () => {
    const svg = svgOf(decls.get('--ragbox') ?? '');
    expect(svg).toBe(ragBox());
    const d = /<path d='([^']+)'\/>/.exec(svg)?.[1] ?? '';
    expect(d.startsWith('M') && d.endsWith('Z')).toBe(true);
    const pts = d.slice(1, -1).split('L').map((p) => p.split(' ').map(Number));
    expect(pts.length).toBeGreaterThan(200);
    for (const [x, y] of pts) {
      expect(x).toBeGreaterThan(0);
      expect(y).toBeGreaterThan(0);
      expect(x).toBeLessThan(132);
      expect(y).toBeLessThan(132);
    }
    for (const corner of [[2.4, 2.4], [129.6, 2.4], [129.6, 129.6], [2.4, 129.6]]) expect(pts).toContainEqual(corner);
    expect(decls.get('--ed-rag')).toBe('var(--ragbox) 6 / 6px round');
    expect(decls.get('--ed-rag-s')).toBe('var(--ragbox) 6 / 3px round');
  });

  // Named change (deferred textures): three rules — the defaults, [data-paint-tex], [data-paint-stroke].
  it('paint.css declares only custom properties, under :root[data-variant="data"]', () => {
    const rules = parseRules(css);
    expect(rules.map((r) => r.selector)).toEqual([SCOPE, TEX, STROKE]);
    expect(splitSelectors(rules[0]!.selector)).toEqual([SCOPE]);
    for (const r of rules) expect([...r.decls.keys()].filter((name) => !name.startsWith('--'))).toEqual([]);
    expect(rules[0]!.decls.size).toBe(6 + 1 + 1 + 2 + 6 + 1);
    // Named change (data CSS external): paint.css reaches data pages through data-site.css, which DataLayout links.
    expect(read('src/styles/data-site.css')).toMatch(/@import '\.\/paint\.css';/);
    expect(read('src/layouts/DataLayout.astro')).toMatch(/data-site\.css\?url/);
    for (const f of ['BaseLayout', 'NeutralLayout']) expect(read(`src/layouts/${f}.astro`), f).not.toContain('paint.css');
  });
});
