// The game exit's oscilloscope traces (MO-38): a sine and a square pulse with a little ringing (odd harmonics 3…11
// with Lanczos sigma factors), computed at build time as SVG path data over a 1000 × 100 box.
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { WAVE, WAVE_STROKES, waveMasks, wavePaths } from '../../src/lib/waveform';

const points = (d: string): [number, number][] => {
  const n = d.replace(/^M/, '').trim().split(/[\s,]+/).map(Number);
  const out: [number, number][] = [];
  for (let i = 0; i < n.length; i += 2) out.push([n[i]!, n[i + 1]!]);
  return out;
};

describe('wavePaths (MO-38)', () => {
  it('wavePaths: sine and square paths span x 0…1000, stay inside the 100-unit box with ringing ≤ 9% overshoot, are deterministic, ≤ 1,500 chars each', () => {
    const a = wavePaths();
    expect(wavePaths()).toEqual(a);
    for (const [name, d] of Object.entries({ sine: a.sine, square: a.square })) {
      expect(d.length, name).toBeLessThanOrEqual(1500);
      expect(d, name).toMatch(/^M-?\d/);
      const p = points(d);
      expect(p.length, name).toBeGreaterThan(60);
      // one period of run-in to the left (the trace travels right by one period), then the box
      expect(p[0]![0], name).toBeLessThanOrEqual(0);
      expect(p.at(-1)![0], name).toBeGreaterThanOrEqual(1000);
      for (const [, y] of p) {
        expect(y, name).toBeGreaterThanOrEqual(0);
        expect(y, name).toBeLessThanOrEqual(100);
      }
    }
    // the square's peak over the pulse's own level stays under 9% (Lanczos-smoothed Gibbs ringing)
    const ys = points(a.square).map(([, y]) => Math.abs(y - 50));
    expect(Math.max(...ys) / (WAVE.amplitude * (4 / Math.PI) * (Math.PI / 4))).toBeLessThanOrEqual(1.09);
    // cycles: the sine is slow, the square faster (2.2 → 4.8 cycles over the box)
    expect(a.sinePeriod).toBeCloseTo(1000 / 2.2, 5);
    expect(a.squarePeriod).toBeCloseTo(1000 / 4.8, 5);
  });

  it('the chooser exit sheet carries the traces as mask images generated by waveMasks (one per trace and stroke width), with their run-in boxes and one-period travel', () => {
    const css = readFileSync('src/styles/chooser-exit.css', 'utf8');
    for (const t of waveMasks()) {
      t.urls.forEach((url, i) => expect(css, `--xg-${t.name}${WAVE_STROKES[i]}`).toContain(`--xg-${t.name}${WAVE_STROKES[i]}: ${url};`));
      expect(css).toContain(`.file--game .xg__${t.name} { left: ${(t.box.left * 100).toFixed(4)}%; width: ${(t.box.width * 100).toFixed(4)}%; --travel: ${(t.travel * 100).toFixed(4)}%; }`);
      expect(t.box.left).toBeLessThan(0);
      expect(t.box.left + t.box.width).toBeCloseTo(1, 9);
      for (const url of t.urls) expect(url).toMatch(/vector-effect='non-scaling-stroke'/);
      for (const url of t.urls) expect(url).not.toMatch(/#[0-9a-f]{3,6}|%23/i); // no colour literal: the mask's alpha only
    }
  });
});

